name: AxRewards
version: '${project.version}'
main: com.artillexstudios.axrewards.AxRewards
api-version: '1.20'
folia-supported: true

permissions:
  axrewards.reload:
    default: op
  axrewards.reset:
    default: op
  axrewards.forceopen:
    default: op
  axrewards.open.default:
    default: true
  axrewards.open.*:
    default: op
  axrewards.help:
    default: true

softdepend:
  - PlaceholderAPI